### ISSUE TITLE
something about code

### ISSUE THREAD

**Issue by zhangshuyun1** [songdejia/siamese-RPN#2]
Sorry to interrupt you.Did you finish your training code and test code？But i didn‘t find your training code.

**Comment by songdejia** [comment]
@zhangshuyun1 Sorry, I haven't complete it.

**Comment by xujiao3628** [comment]
你好，运行code目录下test_siamrpn.py出现以下错误：
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=70 error=3 : initialization error
Traceback (most recent call last):
  File "test_siamrpn.py", line 222, in <module>
    main()
  File "test_siamrpn.py", line 47, in main
    model = model.cuda()
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:70
我的cuda是9.0的
